version: '3.8'
services:
  postgres:
    container_name: thread-db
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thread
      POSTGRES_DB: thread_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
